### ISSUE TITLE
您好，我想问下，这个手机自适应需要怎么配置呢？

### ISSUE THREAD

**Issue by baixuecheng** [liu-xinhui/vue-admin-template#7]
![image](https://user-images.githubusercontent.com/44012446/92444841-06f96080-f1e6-11ea-9a87-feb0984ee64f.png)
![image](https://user-images.githubusercontent.com/44012446/92444869-11b3f580-f1e6-11ea-9994-a5abb6d93687.png)

**Comment by liu-xinhui** [comment]
这种项目无法做到手机端自适应的，element-ui本身就对移动端支持不好，而且管理端会使用到大量表格，表格也不利于自适应。只能禁止手机端自动缩放。
![image](https://user-images.githubusercontent.com/7698511/92447793-504baf00-f1ea-11ea-8079-acee1adbd8ee.png)
删除index.html中的这行代码即可。
最终效果如下
![image](https://user-images.githubusercontent.com/7698511/92447873-69ecf680-f1ea-11ea-811d-2f8b5d6f1e5c.png)

**Comment by baixuecheng** [comment]
好的 ，十分感谢您的告知
